### ISSUE TITLE
일요일에 팀장님께서 주신 ros2_ws를 git clone하여 사용하면 colcon build가 안되는데

### ISSUE THREAD

**Issue by seoyun-5** [Giromi/CAU_ALCP#11]
어떻게 하면 해결할 수 있을까요? 그때 파일에 hansukim이 적혀있어서 안되는거라고 하셨는데
팀장님께서 다시 올려주셔야 하는건가요?? 아니면 해결할 수 있는 방법이 따로 있을까요??

**Comment by mooyo127** [comment]
저도 그래서 cmake랑 폴더경로만 재설정해줘봤는데 잘 안되더라고요.. 조금만 바꿔주면 될 것 같은데

**Comment by Giromi** [comment]
에러 문구가 무엇인가요??

**Comment by Giromi** [comment]
음 일단 대강 유추해볼 수 있는 에러는 다른 컴퓨터에서 빌드한 build log devel 폴더가 있어서 그런거 같은데요.
한번 **src 폴더 제외하고** 지워본 다음에 build해보셔도 에러 나나요?

**Comment by seoyun-5** [comment]
![image](https://github.com/Giromi/CAU_ALCP/assets/162525038/f313259b-80cb-4b7a-8653-870a71f083b7)

**Comment by seoyun-5** [comment]
src 폴더 제외하고 build하면 에러 안 나고 잘 됩니다!

**Comment by Giromi** [comment]
아 지우고 빌드하면 잘 되나요??

**Comment by seoyun-5** [comment]
넵넵

**Comment by Giromi** [comment]
아 다행이네요! 다른 컴퓨터 빌드한거는 호환이 안될때가 많더라고요!
