### ISSUE TITLE
colcon build error

### ISSUE THREAD

**Issue by seoyun-5** [Giromi/CAU_ALCP#12]
아래 사진은 제 오류이고,
![image](https://github.com/Giromi/CAU_ALCP/assets/162525038/28943acb-3f2e-4f9f-ade4-de6f59dbaae0)
이거는 구글링해서 찾아낸건데 sudo rm -rf하기가 너무 무서워서 이슈에 한번 올려봅니당..
![image](https://github.com/Giromi/CAU_ALCP/assets/162525038/70c70ba3-9a7c-49d9-86d5-b2ec0aa79688)
덜덜..
![image](https://github.com/Giromi/CAU_ALCP/assets/162525038/99d9ba3a-5f9f-4818-9da7-e0c23e2fd425)

**Comment by OKsusu1411** [comment]
저 명령어는 log파일만 삭제하는 거라 아마 큰 에러를 야기하진 않을것같긴한데, 전부터 log가 말썽을 부리네요. 우선 정확히 log파일만 저렇게 삭제 해보셔도 좋을것 같습니다.

**Comment by seoyun-5** [comment]
log파일 삭제해도 똑같은 에러가 뜨네요..다른 분들은 udemy 강의 78번 어떻게 해결하셨는지 공유해주시면 감사하겠습니다!!

**Comment by Giromi** [comment]
일단 딱 봤을 때 ws 디렉토리 안에서 한게 아닌거 같군요~
홈 디렉토리 자체가 workspace로 지정한건가요?
