### ISSUE TITLE
한글 키보드 꿀팁 들고 왔습니당

### ISSUE THREAD

**Issue by seoyun-5** [Giromi/CAU_ALCP#13]
우분투에 한글 키보드를 사용하고 싶다면 흔하게 나오는 것이 ibus인데요,
저는 이게 안되더라구요..그래서 fcitx도 해봤는데 또 안되더라구요.....
근데 kime는 깔자마자 세부적인 설정 없이 리부트하니까 바로 한영키 사용 가능해졌습니다!!
kime를 제외한  ibus나 fcitx, uim는 특정 소프트웨어 실행시 한영키 변환이 더디거나 잘 안된다는 단점이 있다고 합니다.
저희는 우분투 22.04버전이니까 알맞은 걸로 다운로드하시면 될 것 같습니다.
이미 다 설정하셨다면 어쩔수 없죠..ㅎㅎ 이상 제가 오늘 2시간동안 머리 꽁꽁 사맨 결과였습니다..
kime 다운로드는 아래 사이트 참고하시면 됩니다!
https://osg.kr/archives/3109

**Comment by Giromi** [comment]
아이고 고생 많으셨네요!
저는 ibus 밖에 몰랐는데
덕분에 다른 방식도 알게 되었네요! 
나중에 ibus 저도 안될 때에는 알려주신 방법 참고해보도록 하겠습니다!
감사합니다ㅏㅏ!

**Comment by OKsusu1411** [comment]
역시 머리깨지면서 하는 리눅스 세팅....
