### ISSUE TITLE
우분투 세팅하다가 이런 버그가 떴습니다. 어떻게하죠?

### ISSUE THREAD

**Issue by Giromi** [Giromi/CAU_ALCP#2]
<img width="576" alt="Screenshot 2024-03-31 at 13 41 06" src="https://github.com/Giromi/CAU_ALCP/assets/60354633/9ea4ba25-d403-4f38-92e8-4b8558677f80">

**Comment by OKsusu1411** [comment]
삭제하세요

**Comment by Jonghyun-Woo** [comment]
아 ㅋㅋ 그렇게 하는거 아닌데
