### ISSUE TITLE
Ubuntu 설치완료하기

### ISSUE THREAD

**Issue by Giromi** [Giromi/CAU_ALCP#4]

**Comment by mooyo127** [comment]
저 우분투 설치 끝났습니다
부팅 때 grub도 뜨는 거 보니 잘 된거 같네요
![image](https://github.com/Giromi/CAU_ALCP/assets/164590109/3d21cebb-4b49-4001-863b-7c7a70c00f93)

**Comment by Giromi** [comment]
> 저 우분투 설치 끝났습니다 부팅 때 grub도 뜨는 거 보니 잘 된거 같네요 ![image](https://private-user-images.githubusercontent.com/164590109/318273171-3d21cebb-4b49-4001-863b-7c7a70c00f93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTI3MTEsIm5iZiI6MTcxMTg5MjQxMSwicGF0aCI6Ii8xNjQ1OTAxMDkvMzE4MjczMTcxLTNkMjFjZWJiLTRiNDktNDAwMS04NjNiLTdjN2E3MGMwMGY5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxMzQwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWEyMDY0NDBjZDhhMDNmODk4YjAzM2VhZDFkNzk4OTQzNmMyODlmODU2MTQ2ZDE2ZjMzZTc3YjZiNmViMzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-xQ0pfQaaJUrAHwQcVu568l6OyarksBXP8ZJMhv61A0)

아이고 고생했네요 ! 하루만에 했다니 정말 열정맨 이시네여 
명령어 내일 테스트 해보세요!

**Comment by mooyo127** [comment]
> > 저 우분투 설치 끝났습니다 부팅 때 grub도 뜨는 거 보니 잘 된거 같네요 ![image](https://private-user-images.githubusercontent.com/164590109/318273171-3d21cebb-4b49-4001-863b-7c7a70c00f93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTI3MTEsIm5iZiI6MTcxMTg5MjQxMSwicGF0aCI6Ii8xNjQ1OTAxMDkvMzE4MjczMTcxLTNkMjFjZWJiLTRiNDktNDAwMS04NjNiLTdjN2E3MGMwMGY5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxMzQwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWEyMDY0NDBjZDhhMDNmODk4YjAzM2VhZDFkNzk4OTQzNmMyODlmODU2MTQ2ZDE2ZjMzZTc3YjZiNmViMzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-xQ0pfQaaJUrAHwQcVu568l6OyarksBXP8ZJMhv61A0)
> 
> 아이고 고생했네요 ! 하루만에 했다니 정말 열정맨 이시네여 명령어 내일 테스트 해보세요!

감사함다 😃

**Comment by Giromi** [comment]
우분투 디스크 분할 프로그램
### disk
### gparted

**Comment by sungsimdang** [comment]
![image](https://github.com/Giromi/CAU_ALCP/assets/164595783/63d55877-fe48-4e5f-9183-62544f13972b)

설치 완료했습니다!

**Comment by OKsusu1411** [comment]
크롬까지 다하셨네요. 한글까지 깔면 끝나겠네요.
혹시 블루투스 마우스나 키보드쓰시는 분들은 윈도우랑 리눅스에서 각각 자동으로 페어링이 안되니 추가로 설정해주셔야 합니다

**Comment by seoyun-5** [comment]
설치완료했습니다!

**Comment by Shiningsun00** [comment]
설치 완료했습니다!

**Comment by Giromi** [comment]
다들 잘하시네요요
