### ISSUE TITLE
다들 통학인가요 자취인가요?

### ISSUE THREAD

**Issue by Giromi** [Giromi/CAU_ALCP#5]
필요하면 자주 만날 수 있는 지 궁금해서.. 이슈로 물어봐요 ㅋㅋ

저는 상도역 자취라서 언제든 학교에서 대면으로 만날 수 있습니다!
**(종현이는 학교에 상시 거주하고 있는 NPC라서 항상 있어요 ㅎㅎ)**

**Comment by sungsimdang** [comment]
상도교회 인근 자취입니다! 310관까지 도보 10분걸려요

**Comment by mooyo127** [comment]
인천 통학입니다.. 1시간 반 거리입니다. 근데 부르시면 언제든지 달려갑니다

**Comment by Giromi** [comment]
> 상도교회 인근 자취입니다! 310관까지 도보 10분걸려요

오 가까우시네요! 열정에 박수를 보냅니다!

**Comment by Giromi** [comment]
> 인천 통학입니다.. 1시간 반 거리입니다. 근데 부르시면 언제든지 달려갑니다

헉.. 1시간 반이면.. 왕복 3시간 이네요 고생이 많습니다 ..

**Comment by Daisy103104** [comment]
기숙사 살고 있습니다!

**Comment by seoyun-5** [comment]
정문에 살고 있습니다!

**Comment by Shiningsun00** [comment]
신촌 통학입니다!
