### ISSUE TITLE
............ㅠ 우분투 부팅이 왜.....안될까요....아무것도 안 했는데 갑자기...안됩니다.....

### ISSUE THREAD

**Issue by seoyun-5** [Giromi/CAU_ALCP#9]
![KakaoTalk_20240510_112617739_02](https://github.com/Giromi/CAU_ALCP/assets/162525038/fa856d83-0906-4d9f-b2f3-7a2c97d1813f)
![KakaoTalk_20240510_113511885](https://github.com/Giromi/CAU_ALCP/assets/162525038/7a4be74e-f9f7-4ee9-8c23-c868fef90d1c)
![KakaoTalk_20240510_112617739](https://github.com/Giromi/CAU_ALCP/assets/162525038/d82a57d3-d73a-4549-b3fc-c991b55ab7bf)
![KakaoTalk_20240510_112617739_01](https://github.com/Giromi/CAU_ALCP/assets/162525038/c2ea1fbc-57d4-4c11-b2cf-d9ea3926b35b)

**Comment by Giromi** [comment]
gnome display manager가 실패했다면... 혹시 최근에 업그레이드한 적 있나요?

**Comment by seoyun-5** [comment]
업그레이드 한 적 없습니다

**Comment by Giromi** [comment]
![image](https://github.com/Giromi/CAU_ALCP/assets/60354633/e08b3e3f-38e3-42da-9d0b-38bd289072b9)
출처
https://askubuntu.com/questions/1375406/ubuntu-20-04-not-booting-stuck-up-at-failed-to-start-gnome-display-manager

제가 겪었을 때에는 그래픽 드라이버 업그레이드를 잘 못해서 발생했는데,
업데이트 하신적이 없다면 위 사이트 원인일 수 있겠군요...
디스크 용량이 충분했을까요?

그래서 해결하려면 우분투 접속을 해야 되는데... 쉽지 않아서 직접 컴퓨터를 좀 봐야겠네요ㅠ


직접 해보시려면 아래 사이트 참고해보시면 좋겠네요~

우분투 진입하는 법(예전에 안켜지는거 아래 사이트 시도 해봤을 때 되었음), 근데 오류가 달라서.. 될지 모르겠음
https://atomic0x90.github.io/ubuntu/2020/08/31/ubuntu-started-gnome-display-manager-freezing.html

**Comment by seoyun-5** [comment]
앗 감사합니다! 한번 해보고 또 올리겠습니다!!

**Comment by seoyun-5** [comment]
![KakaoTalk_20240510_152936766](https://github.com/Giromi/CAU_ALCP/assets/162525038/6a6d9b75-04f0-4a3a-9263-a695cb582d4a)
위 사이트 대로 했는데도 아직도 이렇게 뜨네요 디스크 문제인거 같아서 조금만 더 해결해보겠습니다..

**Comment by seoyun-5** [comment]
디스크가 꽉 찬 것 같아서 다시 디스크 쪼개고 우분투 재설치했습니다!
